### ISSUE TITLE
Do Withdrawal IPNs work correctly?

### ISSUE THREAD

**Issue by Fardinak** [OrahKokos/coinpayments#13]
According to the IPN documentation at https://www.coinpayments.net/merchant-tools-ipn, withdrawal IPN statuses are as follows:
```
0 = Waiting Email Confirmation
1 = Pending
2 = Sent/Completed
```
That conflicts with the general "Payment Statuses" section on the same page which clearly defines `2` as "Queued for nightly payout" and goes on to clarify, anything between `0` and `99` means "Payment is Pending in some way".

**Comment by OrahKokos** [comment]
Thank you for the bug report and sorry for the delay. 
I will try and catch some free time to address all issues for this lib in the coming weeks.
PRs welcome.

**Comment by Fardinak** [comment]
Thank you, for this handy library.
This is more of a clarification request. The CoinPayments documents seem unclear to me on this matter; therefore, I'm asking if this implementation is, in fact, correct. We are still in development and have not tested withdrawals. When we do, I'll update this thread with the answer, if no one already has.

**Comment by Lesther993** [comment]
HI @Fardinak I'm starting using coinpayment, could you give me your opinion about the API so far? The callback addresses and ipn works? which cryptocurrencies have you tested?

**Comment by Fardinak** [comment]
Hi @Lesther993, I've only used Bitcoin so far. There may be some documentation issues, but the API seems stable to me. I didn't face any issues regarding Callback addresses, but IPNs can take a while. You may not get one on the instant that a transaction has been published, but it's pretty stable after that (first confirmation and past that).

This client in particular was very helpful in getting what I wanted faster.

**Comment by Filliposniper** [comment]
Hi @OrahKokos I'm using coinpayment api but i receive an error message when i want to create a transaction, if i set the currency1 to USD and currency2 to LTC and amount e.g 5000 it logs out `'Receiver does not accept that coin!'`. but it works well with some other coin. Any reason for this error

**Comment by LordotU** [comment]
@Filliposniper you should enable accepting LTC in your Coinpayments dashboard. Did you do that?

![Coinapyments dashboard screen](https://i.gyazo.com/65badacdcf0289dd23f9aa0337acb3a7.png)

**Comment by Filliposniper** [comment]
@LordotU  thanks i already solved it i didn't check the option for LTC.. sorry for taking much time to reply

**Comment by Fardinak** [comment]
To follow up, we did test and run our app and the library handled all transactions (including withdrawals) as expected.
