### ISSUE TITLE
Automated IPN crash

### ISSUE THREAD

**Issue by daniel-van-niekerk** [OrahKokos/coinpayments#14]
The automated IPN crash if it receives something it cannot parse. While testing it received html instead of JSON.

Seems to be a reply from proxy or bot checker called Incapsula. Might have to wrap `JSON.parse(data)` in a try/catch.

**Comment by OrahKokos** [comment]
Please note that I plan to drop the auto ipn feature. I'd like to move towards having a clean api wrapper. I will address all issues in the coming weeks.
