### ISSUE TITLE
auto_confirm must be optional

### ISSUE THREAD

**Issue by nyancodeid** [OrahKokos/coinpayments#15]
on README, function createWithdrawal have options auto_confirm that have value 0 or 1 and default value is 1.
But they always set to 1. i can't set auto_confirm to 0 becouse when function called they always set to 1.

```javascript
CoinPayments.prototype.createWithdrawal = function (options, callback) {
    options.cmd = 'create_withdrawal';
    options.auto_confirm = 1;
    return this.request(options, callback);
  };
```

Please fix this you can use Object.assign 
https://developer.mozilla.org/id/docs/Web/JavaScript/Reference/Global_Objects/Object/assign

**Comment by OrahKokos** [comment]
Thank you for the feedback.
I was off for quite some time, but i will address this and all other issues in the coming weeks.
