### ISSUE TITLE
Coinpayments IPN Errors on any POST with a "/" in the body

### ISSUE THREAD

**Issue by duper51** [OrahKokos/coinpayments#16]
Title says it all. Looks like "/" characters are not encoded correctly by the library. A workaround could be to copy how PHP encodes these characters and manually reencode them to that character.

I was thinking of recoding the IPN function to take a "raw body" argument and to use that instead of trying to recover it the way it's done now.

**Comment by OrahKokos** [comment]
Hello, thanks for the feedback.
Currently I am in a "life" situation, but I will address this ( and other issues ) in the coming weeks.
If a fix is simple, please do not shy away from making PRs :)

**Comment by krasota1** [comment]
Hello. can we communicate in telegrams? or I can come to you. we want to make a useful, technical project for students with crypto currency mining and reliable transactions and data storage.
--
Отправлено из Mail.Ru для Android пятница, 29 декабря 2017г., 19:06 +03:00 от Marko Paroski  notifications@github.com :
