### ISSUE TITLE
Middleware 'Complete' IPN never goes through

### ISSUE THREAD

**Issue by namanyayg** [OrahKokos/coinpayments#18]
https://github.com/OrahKokos/coinpayments/blob/master/src/ipn.js#L41

This should be a double equal to operator, or the 100 should be a string ('100') because coinpayments sends statuses as strings.

Took me a lot of while to find why my server was just not responding to "Completed" IPNs :)

**Comment by OrahKokos** [comment]
@namanyayg Thanks for the contribution!
Sorry about maintenance, as seen in other posts, I am quite out of the loop currently...
Lucky for me I have you guys :)

P.S. 2.0 is in the works, where i will be addressing all issues/new features.

**Comment by OrahKokos** [comment]
Merged https://github.com/OrahKokos/coinpayments/pull/19

**Comment by namanyayg** [comment]
No problem! Please don't apologise -- you've done a lot of amazing work already creating this module. Wouldn't have been able to complete the app I'm working on without this at all :)
