### ISSUE TITLE
Remove warnings about migrating to the new version

### ISSUE THREAD

**Issue by damirka** [OrahKokos/coinpayments#39]
Please, remove annoying messages about new version of your software. API V2 looks extremely weird and is not backwards compatible. 

You've changed too much to force this message. And migration to the new version is complicated enough for projects already using 1 version of your lib.

**Comment by OrahKokos** [comment]
Hello,
Current version is 1.1.8 which is equal to 1.1.7 + these messages.
Just downgrade to 1.1.7.

Please consider moving to 2.0.0: https://github.com/OrahKokos/coinpayments/blob/version/2.0.0/MIGRATION.md
