### ISSUE TITLE
How to get all deposit address of an currency?

### ISSUE THREAD

**Issue by ndphuong** [OrahKokos/coinpayments#42]
hi,
How to get all deposit address of an currency?

**Comment by OrahKokos** [comment]
Hello,
If I understand you correctly, you need to get all deposit addresses for all accepted currency? 
If so then:
1. Use https://github.com/OrahKokos/coinpayments#rates with option `accepted` to get all accepted currency.
2. Loop accepted currency and call https://github.com/OrahKokos/coinpayments#get-deposit-address

Hope this helps.
