### ISSUE TITLE
COINPAYMENTS_INVALID_REQUEST

### ISSUE THREAD

**Issue by casha1995** [OrahKokos/coinpayments#43]
COINPAYMENTS_INVALID_REQUEST this message keeps appearing in my console , even that the api is working fine , so i wanna know what may cause such a thing , and how the api payment system is working fine , and in the same time from time to time i get this error message COINPAYMENTS_INVALID_REQUEST , so does some one have idea of what may cause such a problem

**Comment by OrahKokos** [comment]
Hey @casha1995 ,
Does not ring any bells really. Seems like an older version of the lib is used in your use case.
How to fix:
1. Update to 2.x.x
2. Debug. Older versions possible hold hidden gems (bugs). A breakpoint will solve mysteries, it is a very small lib :) 

Sorry for the vague answer. But this is all i can offer.
