### ISSUE TITLE
Regular Expression Fix for MassWithdrawal

### ISSUE THREAD

**Issue by Uter1007** [OrahKokos/coinpayments#45]
Hi,
there is currently a bug in the Masswithdrawal validate function. The given regex only works for wd0-wd9. Please add * to your expression. 

 /wd\[wd[0-9]\]\[(amount|address|currency|dest_tag)\]/;
to
 /wd\[wd[0-9]*\]\[(amount|address|currency|dest_tag)\]/;

I've wanted to create a pull request but I dont have the permissions to do that.

**Comment by OrahKokos** [comment]
Fixed: https://github.com/OrahKokos/coinpayments/pull/46
