### ISSUE TITLE
IPN isn't working

### ISSUE THREAD

**Issue by thedevxen** [OrahKokos/coinpayments#47]
I've been trying to set the IPN address to get the HTTP callback on my server. But IPN doesn't seems working.

```
client.getCallbackAddress(
    {
        currency: 'btc',
        ipn_url: 'https://webhook.site/16732ba6-6427-4eff-8195-ec8604cb8857'
    },
    console.log
);
```

> Here, I used http://webhook.site website just for testing callbacks.

**Comment by OrahKokos** [comment]
Hi @thedevxen,

Not much has changed on any side, regarding IPNs.
Please be sure to follow all the steps required to make the IPN system work. (Account settings -> Merchant Settings -> IPN )
Here is a repo for quick testing ( deploy it elsewhere / outside of your current server ): https://github.com/OrahKokos/coinpayments-ipn-docker

If this does not work, please feel free to open the ticket on this repo: https://github.com/OrahKokos/coinpayments-ipn

IPN processing is no longer a part of this module.
