### ISSUE TITLE
Setting timeout (creating a transaction)

### ISSUE THREAD

**Issue by Vultwo** [OrahKokos/coinpayments#48]
Hello,

I'm not able to set the timeout when creating a transaction. Is this the way it is supposed to be, or is this possible somehow?

**Comment by OrahKokos** [comment]
Hey @Vultwo,

Unfortunately Coinpayments does not support setting a custom timeout.
Official docs: https://www.coinpayments.net/apidoc-create-transaction

Looks like timeout is fixed D: .
