### ISSUE TITLE
Site is down, Coinpayment doesn't work?

### ISSUE THREAD

**Issue by StarNeit** [OrahKokos/coinpayments#49]
{ CoinpaymentsError: Invalid response
7|demo  |     at IncomingMessage.res.on (/root/coinpayments-service/node_modules/coinpayments/lib/index.js:92:27)
7|demo  |     at emitNone (events.js:111:20)
7|demo  |     at IncomingMessage.emit (events.js:208:7)
7|demo  |     at endReadableNT (_stream_readable.js:1064:12)
7|demo  |     at _combinedTickCallback (internal/process/next_tick.js:139:11)
7|demo  |     at process._tickDomainCallback (internal/process/next_tick.js:219:9)
7|demo  |   name: 'CoinpaymentsError',
7|demo  |   message: 'Invalid response',
7|demo  |   extra: 'We are sorry, the website is under maintenance. We should be back shortly.' }

We receive this message when use coinpayment on our project.
Please help!   When does maintenance finish?

**Comment by smupyknight** [comment]
When will it be live again? Our project will die if we can't resolve this issue soon.

**Comment by kgh2927845** [comment]
Coinpayment.net was gone for me, too.
What's issue?
When will it be online?

**Comment by soapbravo** [comment]
Same on my side!
What is going on... This is critical for me.

**Comment by lodestar-sr** [comment]
Oh, It is critical!
It seems it's hacked~

**Comment by StarNeit** [comment]
![image](https://user-images.githubusercontent.com/16525001/68026158-1b5bfb00-fcaf-11e9-8e68-10b183066873.png)

**Comment by bloolight** [comment]
Same issue on my side.

Look forward to get back the website live soon
