### ISSUE TITLE
Better IPN support

### ISSUE THREAD

**Issue by azarus** [OrahKokos/coinpayments#5]
Hi there!
First thanks for your great work! I am using your library to handle coinpayments payments however your current IPN integration is quite messy and hard to read actual states since it only works with express. Using this with sails.js or a custom framework that does not use any low level api of express is not straight forward.

I'd like to propse to have an option to parse custom input for the IPN verification and return a promise instead of executing the next function. This way we are able to reuse the IPN code easily, while this approach still allows to keep the current express middleware solution in place.

I can prepare a PR for this in to time if you're willing to accept an integraton with a promise version of the IPN handling.

Thanks!
Azarus

**Comment by azarus** [comment]
I'll send you an updated documentation and examples for this to better understand my idea if you wish :)

**Comment by OrahKokos** [comment]
Hello Azarus,
Thanks for your continual feedback/contribution. 
I absolutely agree with your statement. I think this will be a good thing for the lib. 
Feel free to drop me a PR, let's keep it clean and documented and preferably with no dependencies. :)

**Comment by azarus** [comment]
Thanks i just submitted a PR.

**Comment by MarkoParoski** [comment]
@azarus IPN support scheduled for 2.0.0
https://github.com/OrahKokos/coinpayments/issues/24

**Comment by azarus** [comment]
@MarkoParoski thanks, sorry i couldn't focus on this was very busy with other stuff.
