### ISSUE TITLE
client.rates options.accepted doesn't work

### ISSUE THREAD

**Issue by codingfornoobsbyanoob** [OrahKokos/coinpayments#50]
Noticed this issue previously as well.

    client.rates({short: 1, accepted: 1})
        .then((result) =>{res.json(result)})
        .catch((err) => {res.json(err)});

short is working but accepted isn't. Returning full list of all coins. 

Below code also returning all coins. 
    client.rates({accepted: 1})
        .then((result) =>{res.json(result)})
        .catch((err) => {res.json(err)});

I'm using version 2.0.3

API key includes rates permission.

**Comment by OrahKokos** [comment]
Looks like API is not responsive, fields are passed in correctly. Problem with the service itself.
