### ISSUE TITLE
I cant import coinpayment using "import" in nest.js framework

### ISSUE THREAD

**Issue by osinakayah** [OrahKokos/coinpayments#51]
[ExceptionHandler] coinpayments_1.default is not a constructor 
TypeError: coinpayments_1.default is not a constructor

**Comment by OrahKokos** [comment]
@osinakayah coinpayments now supports require and import.

**Comment by viktorhugo** [comment]
the same problem happens to me, [ExceptionHandler] coinpayments_1.default is not a constructor
TypeError: coinpayments_1.default is not a constructor
Am I missing something?

**Comment by OrahKokos** [comment]
Reopening this one.
Possible underlying issues

**Comment by Aareksio** [comment]
Reproduced in my TS project.

```ts
import CoinPayments from 'coinpayments';
// UnhandledPromiseRejectionWarning: TypeError: coinpayments_1.default is not a constructor

import * as CoinPayments from 'coinpayments';
const coinPayments = new CoinPayments(options);
// Works, but TypeScript complains about CoinPayments not being a constructor
```

The solution seems to be setting `esModuleInterop: true` inside the project's `tsconfig.json`.
Please note changing the above property may require additional changes in your codebase, as it alters the default import behavior.

**Comment by Otrex** [comment]
Hi, i am new to implementing coinpayment. 
const client = new Coinpayments(credentials:CoinpaymentsCredentials)
is giving me error.

It is saying it expected ',' instead of :

**Comment by OrahKokos** [comment]
Hey @Otrex 
Understand that this is a problem right now. 
Please use try using the workaround which was specified above.
I will be revisiting this repo soon enough to resolve this issue and possibly make a blueprint for 3.0.0. I don't really see a way out of this without introducing breaking changes on how imports are done (avoid default export).

Check back in a few weeks for updates.

**Comment by kibertoad** [comment]
@OrahKokos You can use "infamous triplet" patrern to implement this support in backwards compatible way. Check this: https://github.com/fastify/fastify-funky/blob/main/index.js

**Comment by OrahKokos** [comment]
@kibertoad Thanks man will try it out.

**Comment by OrahKokos** [comment]
All import/export magic should be resolved, with some black magic: https://github.com/OrahKokos/coinpayments/pull/55
