### ISSUE TITLE
I can not set ipn_url when I use 'client.createMassWithdrawal'.

### ISSUE THREAD

**Issue by okahidenobu** [OrahKokos/coinpayments#52]
Hello, 
I want to set ipn_url when I use 'client.createMassWithdrawal' but the api does not recognize the ipn_url.

My code is  like below.
Please teach me how to use.

async function () {
  let result = null

  const withdrawArray = {
      amount: '0.02937',
      currency: 'LTCT',
      address: 'MY ADDRESS',
      add_tx_fee: 1,
      ipn_url: ' MY IPN_URL'
    }

  await client.createMassWithdrawal(withdrawalArray)
    .then(function (res) {
      result = res
    })
    .catch((e) => {
      console.log(e)
    })

  return result
}

**Comment by okahidenobu** [comment]
i can set ipn_url with 'client.createTransaction'.

**Comment by OrahKokos** [comment]
IPN field is not supported in `createMassWithdrawal`. Official docs: https://www.coinpayments.net/apidoc-create-withdrawal
