### ISSUE TITLE
How I can find number of coins I have for a specific coin type.

### ISSUE THREAD

**Issue by UnnikrishnanBhargavakurup** [OrahKokos/coinpayments#6]
How I can find number of coins I have for a specific coin type. I want to know how many "PotCoin" I have in my wallet.

Is there any API for that

**Comment by OrahKokos** [comment]
The API covers rates (in satoshis) and balances. However if you want to display in some other currency you would need to handle it on the application level, using proportions (math) or use some external exchange API.
