### ISSUE TITLE
transaction status

### ISSUE THREAD

**Issue by wiremail** [OrahKokos/coinpayments#61]
hello

when the "Get transaction information" method is called, the transaction status does not change from 0 to 1 when the sender sent funds.

{
time_created: 1617892169,
time_expires: 1617946169,
status: 0,
status_text: 'Waiting for buyer funds...',
type: 'coins',
coin: 'BTC',
amount: 19000,
amountf: '0.00019000',
received: 0,
receivedf: '0.00000000',
recv_confirms: 0,
payment_address: '3QUwN7io7VponpS7ZtYAdYpkH2MkgijvA6'
}

{
time_created: 1617892169,
time_expires: 1617946169,
status: 0,
status_text: 'Waiting for confirms...',
type: 'coins',
coin: 'BTC',
amount: 19000,
amountf: '0.00019000',
received: 19000,
receivedf: '0.00019000',
recv_confirms: 0,
payment_address: '3QUwN7io7VponpS7ZtYAdYpkH2MkgijvA6'
}

as you can see from the api answers both in case 'Waiting for buyer funds...' and in case 'Waiting for confirms...' the status is the same = 0

on the coinpayments page (https://www.coinpayments.net/merchant-tools-ipn) in the "Payment statuses" section it is indicated:
0 = Waiting for buyer funds
1 = We have confirmed coin reception from the buyer

or am I misunderstanding something?

**Comment by OrahKokos** [comment]
Greetings @wiremail, 

To me this message makes sense, due to not having enough confirmations.
The funds are not secured unless X confirmations (blocks) have passed, this is standard practice in the industry. I would suppose after X confirmations that this status would change. 

Let me know if i missed the point, otherwise i will close this ticket.

**Comment by wiremail** [comment]
OK. However, in my opinion, if the status_text has changed, then it is logical to change the status code )

**Comment by OrahKokos** [comment]
I  would not go with high expectations when dealing with this API.
Anyway, its more related to the API itself rather then this community lib, so feel free to write o Coinpayments directly ( i really have no direct contact with them )
