### ISSUE TITLE
Instance of CoinpaymentsError is not CoinpaymentsError

### ISSUE THREAD

**Issue by Ranguna** [OrahKokos/coinpayments#63]
A variable that is instantiated with `CoinpaymentsError` is not an instance of `CoinpaymentsError`.

Here's a basic example:
```ts
import CoinpaymentsError from "coinpayments/dist/error";

const error = new CoinpaymentsError();

assert(error instanceof CoinpaymentsError);
```

I'm guessing it's because tsconfig target is `ES5`.
Would it be possible to change this to `ES6` ?

**Comment by OrahKokos** [comment]
Hey @Ranguna,
Thanks for the feedback and PR. I will come back to this in a few days. Got some life stuff to deal with + would like to re-examine this part of the code. Not sure im a fan of `instanceof` anymore and would like to explore other ways serving these errors.

Thanks for your patience.

**Comment by Ranguna** [comment]
@OrahKokos that's 100% all right, take your time and thanks for letting me know.

As for instanceof, I don't know if there's another good way to go around this since we are extending Error. Unless we used a Symbol to identify coinpayments errors, but I'd prefer instanceof. 

My use case is that I'd like to know when it's a coinpayments error, or another error unrelated with coinpayments, since I'll have different logic to handle each of these cases.

**Comment by OrahKokos** [comment]
@Ranguna Exactly. 
I think the lib is lacking proper error handling, its very basic. I'd like to explore sum types, so all possible error types are defined out of the box. 
But lets talk another day.

**Comment by Ranguna** [comment]
@OrahKokos Man that would be amazing to have!

Whenever you're ready :+1:

**Comment by OrahKokos** [comment]
https://github.com/OrahKokos/coinpayments/discussions/68

**Comment by OrahKokos** [comment]
Coinpayments 2.1.3 is published.
```javascript
import { Coinpayments } from "coinpayments";
import CoinpaymentsError from 'coinpayments/dist/error/index'

const credentials = {
  key: '[redacted]',
  secret: '[redacted]'
}

const client = new Coinpayments(credentials);

(async () => {
  try {
    const tx = await client.getTx({ txid: 'Bogus-ThrowError-Plox' })
    console.log(tx)
  } catch (e) {
    console.log('Exception')
    console.log('Exception Constructor', e.constructor, e instanceof CoinpaymentsError)
  }
})();
```
