### ISSUE TITLE
Can't resolve 'crypto'

### ISSUE THREAD

**Issue by pawankumarjoshi** [OrahKokos/coinpayments#65]
./node_modules/coinpayments/dist/internal.js
Module not found: Error: Can't resolve 'crypto' in 'D:\Raven\RavenFrontend\node_modules\coinpayments\dist'

I am getting this error once i call create transaction api.

**Comment by OrahKokos** [comment]
Greetings friend.
This seems to be your development env issue. 'crypto' is a core nodeJS lib that should be available if you run your env properly.
Good luck

**Comment by pawankumarjoshi** [comment]
Thanks I was trying to use transaction api in angular, Now working with nodeJS. Thanks Again.
