### ISSUE TITLE
Get Exchange Rates / Supported Coins API doesn't return accepted coins only

### ISSUE THREAD

**Issue by mlstoppa** [OrahKokos/coinpayments#67]
Hi all,
I am trying to get the whole list of accepted currencies on the settings page and I thought client.rates was the right API.
According to the documentation, the accepted parameter set to 1 should limit the result set to the enabled coins only, but it is not true: all of the currencies are returned in the JSON data no matter if they are enabled or not. A further filter must be applied to the result set to get enabled currencies only.
It seems the "accepted" parameter is not honored.
Thank you

**Comment by OrahKokos** [comment]
https://github.com/OrahKokos/coinpayments/discussions/68

**Comment by OrahKokos** [comment]
@mlstoppa Tested things out it seems if you set ```accepted: 2``` you get the desired result.
```accepted: 1``` is indeed not honored, however this seems to be a problem with Coinpayments service itself.
Just use ```2``` Closing
