### ISSUE TITLE
CoinpaymentsCreateMassWithdrawalElement not supporting currency2

### ISSUE THREAD

**Issue by rajeshdalsaniya** [OrahKokos/coinpayments#73]
As per API document and also in other library like [CoinPayments PHP](https://github.com/CoinPaymentsNet/coinpayments-php/blob/0ea62e2105c666a8ff9b004c4116f2574857acb7/examples/mass_withdrawal.php) etc supporting mass withdrawal with currency2 it should be like

```
export interface CoinpaymentsCreateMassWithdrawalElement  {
  amount: number;
  currency: string;
  currency2?: string;
  dest_tag?: string;
}
```

Kindly update it thanks

**Comment by OrahKokos** [comment]
@rajeshdalsaniya Looks like the API was updated in more places then this one. Will write up 2.2.0 to include all the changes.

**Comment by OrahKokos** [comment]
https://github.com/OrahKokos/coinpayments/releases/tag/2.2.0
