### ISSUE TITLE
querystring deprecation with latest webpack

### ISSUE THREAD

**Issue by alexnoise79** [OrahKokos/coinpayments#74]
updating new version of angular, i got this error

`./node_modules/coinpayments/dist/internal.js:56:20-42 - Error: Module not found: Error: Can't resolve 'querystring' in 'D:\Code\frontend-monorepo\node_modules\coinpayments\dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "querystring": require.resolve("querystring-es3") }'
        - install 'querystring-es3'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "querystring": false }
`

**Comment by OrahKokos** [comment]
@alexnoise79 This is a backend lib.
Using this lib on FE a big security risk for public and for private its a small security risk. 
Anyway you turn it its a security risk and a backend lib.
https://github.com/OrahKokos/coinpayments/issues/56

**Comment by alexnoise79** [comment]
@OrahKokos ok thanks for the advice, anyway querystring lib is deprecated
