### ISSUE TITLE
 CORS error when using CoinPayments API from Next.js application

### ISSUE THREAD

**Issue by ossamax** [OrahKokos/coinpayments#79]
I'm attempting to integrate the CoinPayments API into my Next.js application using the coinpayments npm package. However, when I try to create a new transaction using the createTransaction method, I receive the following error:

``` 
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://www.coinpayments.net/api.php. (Reason: CORS header 'Access-Control-Allow-Origin' missing). Status code: 403
```
 
 I believe this error is related to Cross-Origin Resource Sharing (CORS) restrictions that prevent my Next.js application from making requests to the CoinPayments API. I've tried setting the mode option to no-cors when making the request, but this doesn't seem to resolve the issue.

Can you provide guidance on how to resolve this issue? Do I need to configure my server to allow cross-origin requests, or is there a way to configure the coinpayments package to handle CORS headers correctly?

Thanks for your help!

**Comment by OrahKokos** [comment]
Greetings @ossamax 
The CORS headers thing is a known issue: https://github.com/OrahKokos/coinpayments/issues/56

In short, this module is server-to-server communication, when you are making requests via frontend (from some origin) coinpayment servers will decline this request.
