### ISSUE TITLE
How to use coinpayments.getTx?

### ISSUE THREAD

**Issue by A7DC** [OrahKokos/coinpayments#80]
Hey thanks for the library, it works great for mwe when I create a transaction but when I go to view it I get problems...

I have an api router in nextjs. `pages/api/checkout`

    import { coinpayments } from "../../../initCoinpayments";
    
    export default async function handler(req, res) {
      const { id } = req.query;
    
      try {
        const transactionInfo = await coinpayments.getTx({ txid: id });
        res.status(200).json(transactionInfo);
      } catch (error) {
        console.error("Error fetching transaction info:", error);
        res.status(500).json({ error: "An error occurred while fetching transaction info." });
      }
    }

and then inside `pages/checkout` I have:

    import Container from "@/components/Container";
    import { supabase } from "../../../initSupabase";
    import { useUser } from "@supabase/auth-helpers-react";
    import { useEffect, useState } from "react";
    import PageTitle from "@/components/PageTitle";
    import { coinpayments } from "../../../initCoinpayments";
    
    export default function Document() {
      const user = useUser(); // Get the authenticated user
      const [checkoutData, setCheckoutData] = useState(null);
      const [loading, setLoading] = useState(false);
    
      useEffect(() => {
        setLoading(true);
      
        async function fetchCheckout() {
          if (user) {
            let { data: checkoutData, error: checkoutError } = await supabase
              .from('checkout')
              .select('*')
              .eq('user', user.id)
              .order('created_at', { ascending: false })
              .limit(1);
      
            if (checkoutError) {
              console.error("Error fetching checkout data:", checkoutError);
            }
      
            if (checkoutData && checkoutData.length > 0) {
              const latestCheckout = checkoutData[0];
              setCheckoutData(latestCheckout);
      
              if (latestCheckout.txn_id) {
                try {
                  const response = await fetch(`/api/checkout?id=${latestCheckout.txn_id}`);
                  const transactionInfo = await response.json();
                  console.log("Transaction Info:", transactionInfo);
                  // Do something with the transactionInfo, like updating state
                } catch (error) {
                  console.error("Error fetching transaction info:", error);
                }
              }
            }
          }
      
          setLoading(false);
        }
      
        fetchCheckout();
      }, [user, setCheckoutData]);
      
    
      return (
        <>
          <Container>
            <PageTitle>Checkout</PageTitle>
            {checkoutData && <CheckoutInfo data={checkoutData} />}
          </Container>
        </>
      )
    }
    
    const CheckoutInfo = ({ data }) => {
      return (
        <div className='mw-96'>
          <div className="text-lg font-bold text-center">
            {data.amount} {data.currency2}
          </div>
          <img src={data.qrcode_url} alt="QR Code" className="block mx-auto my-4" />
    
          <p className="mb-2">
            <strong>Created At:</strong> {new Date(data.created_at).toLocaleString()}
          </p>
          <p className="mb-2">
            <strong>Transaction ID:</strong> {data.txn_id}
          </p>
          {/* <p className="mb-2">
            <strong>Not working? Complete on coinpayment.net</strong> <a href={data.checkout_url}>{data.checkout_url}</a>
          </p> */}
          <p className='w-100 block text-wrap'>{data.address}</p>
        </div>
      );
    };

Which returns a 500 error to the console:

    Transaction Info: {error: 'An error occurred while fetching transaction info.'}

What am I doing wrong here? The api key works for creating the transaction but not for this particular function?

Here's the full error from the terminal where I'm running `npm run dev`

    Error fetching transaction info: CoinpaymentsError: This API Key does not have permission to use that command!
        at IncomingMessage.<anonymous> (/home/dan/Documents/code/banana/node_modules/coinpayments/dist/internal.js:91:35)
        at IncomingMessage.emit (node:events:525:35)
        at endReadableNT (node:internal/streams/readable:1358:12)
        at processTicksAndRejections (node:internal/process/task_queues:83:21) {
      extra: {
        data: {
          error: 'This API Key does not have permission to use that command!',
          result: []
        }
      }
    }

**Comment by OrahKokos** [comment]
Greetings @A7DC,
Sorry for the delayed response, hopefully you have figured it out by now.
I'm not that active on coinpayments lately...
2 points:
- This is not a frontend module and using it in the frontend is a major security risk, so i would advise against it.
- You have an issue with permissions on your API key - In coinpayments account screen you are able to select what permissions are associated with the API key that you are using. Go check this option and you should be ok.
