### ISSUE TITLE
Integration Fix

### ISSUE THREAD

**Issue by ErmanCalis2017** [OrahKokos/coinpayments#9]
I tried to connect this api to my meanstack app.
But I got a error.
Can I integrate this node module to my app successfully?

-------
Unhandled rejection Error: TypeError: CoinPayments.on is not a function
    at /Users/dragon/Desktop/bitter_handlebar/node_modules/meanstack/lib/foundation/Application.js:80:19
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at App.resolveProvider (/Users/dragon/Desktop/bitter_handlebar/node_modules/meanstack/lib/foundation/Application.js:79:15)
    at App.bootstrap (/Users/dragon/Desktop/bitter_handlebar/node_modules/meanstack/lib/foundation/Application.js:60:10)
    at bootstrap (/Users/dragon/Desktop/bitter_handlebar/bootstrap/index.js:26:15)
    at Object.<anonymous> (/Users/dragon/Desktop/bitter_handlebar/index.js:8:23)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
--------

My code is 

---------
let 
  CoinPayments = require('coinpayments'),
  express      = require('express'),
  bodyParser   = require('body-parser');

let app = express();

app.use(bodyParser.urlencoded({ extended: true }));

let events = CoinPayments.events;

let middleware = [
  CoinPayments.ipn({
    'merchantId': 'My merchantid',
    'merchantSecret': 'My IPN Secret'
  }), 
  function (req, res, next) {
    // Handle via middleware
    console.log(req.body);
  }]

app.use('/', middleware);

// Handle via instance
CoinPayments.on('ipn_fail', function(data){
    // Handle failed transaction
    console.log("IPN FAIL");
    console.log("coin: " + data);
});
CoinPayments.on('ipn_pending', function(data){
    // Handle pending payment
    console.log("IPN PENDING");
    console.log("coin: " + data);
});
CoinPayments.on('ipn_complete', function(data){
    // Handle completed payment
    console.log("IPN COMPLETE");
    console.log("coin: " + data);
});

// Handle via static field ( can be used in other files, aka no need to init )
events.on('ipn_fail', function(data){
    // Handle failed transaction
    console.log("IPN FAIL");
    console.log("event: " + data);
});
events.on('ipn_pending', function(data){
    // Handle pending payment
    console.log("IPN PENDING");
    console.log("event: " + data);
});
events.on('ipn_complete', function(data){
    // Handle completed payment
    console.log("IPN COMPLETE");
    console.log("event: " + data);
});

**Comment by ErmanCalis2017** [comment]
My goal is that integrate payment system via coinpayments to my website.
Payment system is to receive and give bitcoins between users and admin via coinpayment.
But this node module is not easy to integrate to my web app.
My web app is built with Meanstack.
Could you explain me more details and give me exact code?
Thank you.

**Comment by OrahKokos** [comment]
Hello @ErmanCalis2017,
If you are including it in the backend, please npm update the lib, there was one version which was a flop.
If you are including it in the frontend, then it has no integration ( or anything for that matter ).

A new version is on its way and i will most likely include builds for the browser ( in a day or two )
Did I get you right on this?

**Comment by ErmanCalis2017** [comment]
Hello.
IPN does not works well.
I do not know well about IPN setup.
I did follow

**Comment by ErmanCalis2017** [comment]
Hello.
IPN does not works well.
I do not know well about IPN setup.
I did follow: https://www.coinpayments.net/merchant-tools-ipn

But I can not get any IPN history in coinpayments service.
![1](https://user-images.githubusercontent.com/30188827/30396178-ac2da522-987d-11e7-8ccf-7c5428cd43b7.png)

What is the problem?

**Comment by ErmanCalis2017** [comment]
Hello.
IPN does not works well.
I do not understand well about IPN setup.
I did follow: https://www.coinpayments.net/merchant-tools-ipn

For example, when user's account send bitcoin to me, my admin account has not received deposit IPN history, but only withdrawal IPN history.
I set IPN secret strongly and set IPN url.
I can not get any desposit IPN history in coinpayments service.

**Comment by ErmanCalis2017** [comment]
Hello.
Thanks for your reply.
In coinpayments.net, I can see withdrawal IPN history, but can't see deposit IPN history.
What is the problem?
Are there any problems in my coinpayment account?

**Comment by OrahKokos** [comment]
@ErmanCalis2017 from the docs: 

> Get a deposit address. This action does not include a fee and will not trigger IPN

Hope this clarifies your question

**Comment by ErmanCalis2017** [comment]
Thank you for your help.

**Comment by ErmanCalis2017** [comment]
Then How can I get deposit history?
Is it possible to get notification when user send bitcoin to admin?
Please show me example.
This module is not easy to integrate to my app.

**Comment by OrahKokos** [comment]
Deposit is designed to be self serving ( since no fee ), there is no official way to get deposit history from what i know. 
https://github.com/OrahKokos/coinpayments#getcallback

Is your alternative ( but ofc it includes a fee ).

**Comment by ErmanCalis2017** [comment]
The problem is not fee.
I want to know how to get deposit history or get trigger when user send bitcoin to admin(me).

**Comment by OrahKokos** [comment]
Then use getcallback. It will include a fee and will trigger IPN

**Comment by ErmanCalis2017** [comment]
app.post("/acceptbitcoin", function(req, res) {
    client.getCallbackAddress("BTC", function (err, response) {
    });
});
Is this right?

**Comment by ErmanCalis2017** [comment]
var CoinPayments = require('coinpayments');
var client = new CoinPayments({
                  'key': 'api key',
                  'secret': 'api secret'
                 });

app.post("IPN url", acceptbitcoin, function(req, res) {
    var middleware = [
      client.ipn({
        'merchantId': 'merchant id',
        'merchantSecret': 'IPN secret'
      }), 
      function (req, res, next) {
        // Handle via middleware
      }];
    
    app.use('/', middleware);
    
    // Handle via instance
    
    client.getCallbackAddress("BTC", function (err, response) {
    });
})

Is this right?

**Comment by ErmanCalis2017** [comment]
Could you give me the sample code about that?
Thank you.

**Comment by ErmanCalis2017** [comment]
Hello.
I updated npm lib, but still get a same error.

----------------------------------------------------
Unhandled rejection Error: TypeError: CoinPayments.on is not a function
    at /home/walleter/public_html/node_modules/meanstack/lib/foundation/Application.js:80:19
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at App.resolveProvider (/home/walleter/public_html/node_modules/meanstack/lib/foundation/Application.js:79:15)
    at App.bootstrap (/home/walleter/public_html/node_modules/meanstack/lib/foundation/Application.js:60:10)
    at bootstrap (/home/walleter/public_html/bootstrap/index.js:26:15)
    at Object.<anonymous> (/home/walleter/public_html/index.js:8:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:502:3

**Comment by OrahKokos** [comment]
Hey, make sure package-lock.json has the ticked version. 
The current version works. 
If you are trying to include it in frontend, please browserify it ( EventEmitter is not present in the browser, this is why Coinpayments.on is probably failing ). This lib is made for CJS,
